# Full Example: https://github.com/geekan/MetaGPT/blob/main/config/config2.example.yaml
# Reflected Code: https://github.com/geekan/MetaGPT/blob/main/metagpt/config2.py
llm:
  api_type: "openai"  # or azure / ollama / open_llm etc. Check LLMType for more options
  model: "claude-3-5-sonnet-v2"  # or gpt-3.5-turbo-1106 / gpt-4-1106-preview
  base_url: "https://oneapi.deepwisdom.ai/v1"  # or forward url / other llm url
  api_key: "sk-2MW0o9oxInp36eaJ23E937C93aDa479cBd4922FcEd2c2a55"