"""
Supabase Manager

Supabase only provides a [SDK](https://github.com/supabase/supabase-py) for [REST API](https://supabase.com/docs/guides/api) which is used for table queries, but lacks management capabilities like creating tables and executing SQL.

Therefore, a management SDK is needed to wrap the [Management API](https://supabase.com/docs/reference/api/introduction).
"""

from typing import Any, Optional

from pydantic import BaseModel, Field

from metagpt.config2 import Config
from metagpt.configs.supabase_config import SupabaseConfig
from metagpt.tools.tool_registry import register_tool
from metagpt.utils.ahttp_client import apost


@register_tool(include_functions=["execute_sql", "get_session_schemas"])
class SupabaseManager(BaseModel):
    config: SupabaseConfig = Field(default=Config.default().supabase, description="The Supabase config")

    @property
    def is_supabase_enabled(self) -> bool:
        return self.config.enable

    @property
    def default_headers(self) -> dict:
        return {"Authorization": f"Bearer {self.config.access_token}", "Content-Type": "application/json"}

    async def execute_sql(self, sql: str, project_ref: Optional[str] = None, timeout: int = 10) -> Any:
        """Execute SQL query on Supabase database.

        Args:
            sql: SQL query to execute.
            project_ref: Supabase project ref, defaults to config.project_ref.
            timeout: Request timeout in seconds, defaults to 10.

        Returns:
            dict: Response from the database query

        Example:
            # Create a table with indexes and RLS policies.
            >>> sql = '''
            ... -- Create scores table
            ... CREATE TABLE IF NOT EXISTS scores (
            ...     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            ...     user_email TEXT NOT NULL,
            ...     score INTEGER NOT NULL,
            ...     created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
            ... );
            ...
            ... -- Create indexes for query optimization
            ... CREATE INDEX IF NOT EXISTS scores_user_email_idx ON scores(user_email);
            ... CREATE INDEX IF NOT EXISTS scores_score_idx ON scores(score DESC);
            ...
            ... -- Setup Row Level Security (RLS)
            ... ALTER TABLE scores ENABLE ROW LEVEL SECURITY;
            ... CREATE POLICY "allow_read_all_scores" ON scores FOR SELECT USING (true);
            ... CREATE POLICY "allow_insert_own_scores" ON scores
            ...     FOR INSERT TO authenticated
            ...     WITH CHECK (auth.jwt() ->> 'email' = user_email);
            ... '''
            >>> result = await execute_sql(sql)
        """
        url = f"{self.config.management_base_url}/projects/{project_ref or self.config.project_ref}/database/query"

        return await apost(url=url, json={"query": sql}, as_json=True, headers=self.default_headers, timeout=timeout)

    async def get_session_schemas(
        self,
        session_id: str,
        project_ref: Optional[str] = None,
        db_name: str = "public",
        timeout: int = 10,
    ) -> list[dict[str, str]]:
        """Get database schemas for a specific session_id.

        Args:
            session_id: A unique session identifier generated for each chat. Used for creating isolated database tables and managing development environments.
            project_ref: Supabase project ref, defaults to config.project_ref.
            db_name: Database schema name, defaults to 'public'.
            timeout: Request timeout in seconds, defaults to 10.

        Returns:
            list: A list of tables with their column definitions.

        Examples:
            # Get tables for specific session_id
            >>> session_schemas = await get_session_schemas(session_id="abc12")
            >>> print(session_schemas)
            [
                {
                    "table_name": "todo_abc12_tasks",
                    "columns": "id bigint NOT NULL\ntitle text NOT NULL\nuser_email text NOT NULL"
                },
                {
                    "table_name": "notes_abc12_items",
                    "columns": "id bigint NOT NULL\ncontent text\nuser_email text NOT NULL"
                }
            ]
        """

        return await self._get_database_schemas(
            session_id=session_id, project_ref=project_ref or self.config.project_ref, db_name=db_name, timeout=timeout
        )

    async def _get_database_schemas(
        self,
        project_ref: Optional[str] = None,
        db_name: str = "public",
        timeout: int = 10,
        session_id: Optional[str] = None,
    ) -> list[dict[str, str]]:
        """Get complete database schema information from Supabase including table names and their columns.

        Args:
            project_ref: Supabase project ref, defaults to config.supabase.project_ref.
            db_name: Database schema name, defaults to 'public'.
            timeout: Request timeout in seconds, defaults to 10.
            session_id: A unique session identifier generated for each chat. Used for creating isolated database tables and managing development environments.

        Returns:
            list: A list of tables with their column definitions.

        Examples:
            # Get all tables
            >>> schemas = await _get_database_schemas()
            >>> print(schemas)
            [
                {
                    "table_name": "users",
                    "columns": "id bigint NOT NULL\nemail text NOT NULL\ncreated_at timestamp"
                }
            ]

            # Get tables for specific session_id
            >>> session_schemas = await _get_database_schemas(session_id="abc12")
            >>> print(session_schemas)
            [
                {
                    "table_name": "todo_abc12_tasks",
                    "columns": "id bigint NOT NULL\ntitle text NOT NULL\nuser_email text NOT NULL"
                },
                {
                    "table_name": "notes_abc12_items",
                    "columns": "id bigint NOT NULL\ncontent text\nuser_email text NOT NULL"
                }
            ]
        """

        query = f"""
        SELECT 
            t.table_name,
            string_agg(
                c.column_name || ' ' || c.data_type || 
                CASE WHEN c.is_nullable = 'NO' THEN ' NOT NULL' ELSE '' END,
                E'\n'
            ) as columns
        FROM 
            information_schema.tables t
            JOIN information_schema.columns c 
                ON t.table_name = c.table_name 
                AND t.table_schema = c.table_schema
        WHERE 
            t.table_schema = '{db_name}'
            AND t.table_type = 'BASE TABLE'
        GROUP BY 
            t.table_name
        ORDER BY 
            t.table_name;
        """
        url = f"{self.config.management_base_url}/projects/{project_ref}/database/query"

        table_schemas = await apost(
            url, json={"query": query}, as_json=True, headers=self.default_headers, timeout=timeout
        )

        if session_id:
            table_schemas = [schema for schema in table_schemas if session_id in schema["table_name"]]

        return table_schemas


supabase_manager_instance = SupabaseManager()
